spring:
  datasource:
    url: jdbc:postgresql://db.ostditakoibxmeysltys.supabase.co:5432/postgres?currentSchema=riyatuitionapp&sslmode=require
    username: postgres
    password: vaishu@210504
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    initialization-mode: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 7070
  servlet:
    context-path: /api

session:
  timeout: 300000
